### ISSUE TITLE
Linux platform issues

### ISSUE THREAD

**Issue by Bonefest** [travisvroman/kohi#1]
Hello. I've been following your tutorial and sadly has encountered a problem. On my system the uninitialized event variable has a exactly a nullptr value and message handling was not working correct.

See:
https://github.com/travisvroman/kohi/blob/cc1955cc6b3c2ee163990c5625bef1dde73797a6/engine/src/platform/platform_linux.c#L183-L189

Also, it seems like your loop through screens is actually pointless, since it starts from zero and condition s > 0 fails instantly.

See:
https://github.com/travisvroman/kohi/blob/cc1955cc6b3c2ee163990c5625bef1dde73797a6/engine/src/platform/platform_linux.c#L72

Sorry if I'm incorrect and thanks in advance for any replies.

**Comment by travisvroman** [comment]
First, thank you for this, I appreciate the feedback.

I will look into the first issue and see what's going on. It's possible I missed something there.

As for the second issue, I am aware of it as well, as it was brought up in one of the comments on that video. Screen enumeration wasn't something that was needed - I'd put it in there for demonstration purposes but didn't actually wind up using/testing it, so it'll likely just be removed.

**Comment by Bonefest** [comment]
Ok, thanks for your answer!
