### ISSUE TITLE
[BUG] Windows console attribute not reset after printing.

### ISSUE THREAD

**Issue by beewyka819** [travisvroman/kohi#108]
**Describe the bug**
The Windows console attribute needs to be reset after it is written to, otherwise the previously set attribute will continue to be set until it is changed again.

While this does not cause issues within Kohi itself (as every print sets its own attribute), it can cause issues after program execution finishes. See the screenshot below, which shows what happens when the program execution ends after a FATAL error occurs.

**Screenshots**
![image](https://user-images.githubusercontent.com/8059789/205812211-55ce9c66-9de8-4667-b321-5dfa31624e6e.png)

**Comment by beewyka819** [comment]
PR #109 created to address this issue.

**Comment by travisvroman** [comment]
Thank you for submitting this! Wound up having to tweak the code some from what was in the provided PR, so used that instead.
