### ISSUE TITLE
[BUG] Missing version.h file

### ISSUE THREAD

**Issue by adibMurad** [travisvroman/kohi#136]
**core/engine.c** includes **version.h** which is absent from code base.

Just clone the main branch, open Kohi workspace and **engine.c** source file.

Probably just missing a push?

**Comment by travisvroman** [comment]
Hi, and thanks for reporting this! This was a bug in the build system. This was fixed in a future commit here: https://github.com/travisvroman/kohi/commit/4f0a4dc12ce81d417cfe68e2631cd7fe60fd66f3
