### ISSUE TITLE
[BUG] Using addresses of local variables that goes out of scope

### ISSUE THREAD

**Issue by tstanisl** [travisvroman/kohi#137]
**Describe the bug**
Any usage an address of a local variable that goes out of scope invokes Undefined Behavior.

**To Reproduce**
None need. Errors can be detected by adding `-fsanitize=undefined,address` to compilation options.

**Additional context**

Issue 1.

https://github.com/travisvroman/kohi/blob/4f0a4dc12ce81d417cfe68e2631cd7fe60fd66f3/vulkan_renderer/src/renderer/vulkan/vulkan_device.c#L74

```
 for (u32 i = 0; i < index_count; ++i) {
        ...
        f32 queue_priority = 1.0f;
        queue_create_infos[i].pQueuePriorities = &queue_priority;
    }
```
The pointer `&queue_priority` is invalid after the loop body is executed.

Issue 2.

https://github.com/travisvroman/kohi/blob/4f0a4dc12ce81d417cfe68e2631cd7fe60fd66f3/vulkan_renderer/src/renderer/vulkan/vulkan_pipeline.c#L134

```
    if (config->push_constant_range_count > 0) {
        ...
        VkPushConstantRange ranges[32];
        ...
        pipeline_layout_create_info.pPushConstantRanges = ranges;
    }
```
The `ranges` is no longer valid after body of `if` branch is completed.

Proposed solution is moving declarations to a higher scope.

**Comment by travisvroman** [comment]
Thank you for pointing these out! It's amazing this worked at all 🤣
