### ISSUE TITLE
[BUG] Sizes wrongly defined in defines.h

### ISSUE THREAD

**Issue by FocusFire** [travisvroman/kohi#138]
**Describe the bug**
Giga/Mega/Kilobytes are wrongly defined in defines.h
https://github.com/travisvroman/kohi/blob/4f0a4dc12ce81d417cfe68e2631cd7fe60fd66f3/engine/src/defines.h#L221-L226

**To Reproduce**
1. Use one of the macros to calculate defined type.

**Expected behavior**
To correct constant to be inserted.

**Screenshots**
Does not apply 

**Desktop (please complete the following information):**
 Does not apply

**Smartphone (please complete the following information):**
Does not apply

**Additional context**
https://youtu.be/W-y6qSUOTw0
Timestamp: 1:24:22

**Comment by tstanisl** [comment]
It may be a good idea to add `()` around `amount`. Just in case if someone does `KILOBYTES(x ? 1 : 2)`.
