### ISSUE TITLE
[FEATURE] Setting proper flags in c_cpp_properties.json

### ISSUE THREAD

**Issue by S-Marais** [travisvroman/kohi#15]
Currently on Linux the intellisense is annoyed by the `clock_gettime(CLOCK_MONOTONIC, &now);` situation.

This fix is simple actually and requires a simple change to `cStandard` to be set to `gnu17` instead of `c17`

**Comment by travisvroman** [comment]
Thank you for this! Was also able to resolve this by adding `_GNU_SOURCE` to defines.
