### ISSUE TITLE
[BUG] Windows build system seems out of date

### ISSUE THREAD

**Issue by Mupu** [travisvroman/kohi#167]
**Describe the bug**
I tried building the engine on Windows but had multiple problems.
1. In [Image 1](https://github.com/travisvroman/kohi/assets/2691299/6fd82071-f0a8-42a2-8bbb-60a5a7957eff), the makefile uses two commands that are not present on windows. To get around it I installed busybox and replaced 'tr' with 'busybox tr' and 'sed' with 'busybox sed'. I don't think this should be the solution tho. It was just a quick fix suggested by the discord.
2. In [Image 2](https://github.com/travisvroman/kohi/assets/2691299/d579e9b8-b398-4fb5-8dc2-3ca268f244cd), theres a -Werror. To fix it I just changed u32 to i32 for 'i' inside the loop.
3. In [Image 3](https://github.com/travisvroman/kohi/assets/2691299/2b37c45e-102d-4ee5-b450-313836b4a8fb), im getting unresolved symbols, was fixed by adding KAPI to both functions.

**To Reproduce**
1. Download clang + vulkan sdk
4. run .\build-all.bat windows build debug'

**Expected behavior**
It should just build all.

**Desktop (please complete the following information):**
 - OS: Windows

**Screenshots**
![Image 1](https://github.com/travisvroman/kohi/assets/2691299/6fd82071-f0a8-42a2-8bbb-60a5a7957eff)
![Image 2](https://github.com/travisvroman/kohi/assets/2691299/d579e9b8-b398-4fb5-8dc2-3ca268f244cd)
![Image 3](https://github.com/travisvroman/kohi/assets/2691299/2b37c45e-102d-4ee5-b450-313836b4a8fb)

**Comment by travisvroman** [comment]
Thanks for reporting this! This has been updates/fixed in the soon-to-be-merged `standard_ui` branch.
