### ISSUE TITLE
[FEATURE] _darray_push returns the pointer to new array, but darray_push macro doesnt let the return value be used.

### ISSUE THREAD

**Issue by 2nafish117** [travisvroman/kohi#17]
**Is your feature request related to a problem? Please describe.**
currently the macro`darray_push` doent allow to reassign the modified array pointer after the push. like so.
`array = darray_push(array, value)`
because of the way it resizes internally, it may return a different pointer when resized.

**Describe the solution you'd like**
making the macro a direct passthrough would solve it, but inserting temprary/constant values would need an extra line of code.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by travisvroman** [comment]
Just an FYI, darrays are on a list to be refactored, and this is one of the points that will be addressed.

**Comment by travisvroman** [comment]
Closing this in favour of #48, which is slated to fix this.
