### ISSUE TITLE
images_in_flight type duality

### ISSUE THREAD

**Issue by EliBukchin** [travisvroman/kohi#19]
**Description**
I have notices that vulkan_context.images_in_flight is declared as: vulkan_fence**
but 

- initialized as: vulkan_fence* 
https://github.com/travisvroman/kohi/blob/202ac72822b797288229ac85ddc29f7c73bcc9c2/engine/src/renderer/vulkan/vulkan_backend.c#L225

- used here as vulkan_fense*
https://github.com/travisvroman/kohi/blob/202ac72822b797288229ac85ddc29f7c73bcc9c2/engine/src/renderer/vulkan/vulkan_backend.c#L490

- and used as: vulkan_fense** here:
 https://github.com/travisvroman/kohi/blob/202ac72822b797288229ac85ddc29f7c73bcc9c2/engine/src/renderer/vulkan/vulkan_backend.c#L493
https://github.com/travisvroman/kohi/blob/202ac72822b797288229ac85ddc29f7c73bcc9c2/engine/src/renderer/vulkan/vulkan_backend.c#L498

**Effect**
Currently, there is no side effects as (void*) and VkFence are the same size. but as the code expands, this could end in invalid usage of this variable.

**Mitigation**

L225: context.images_in_flight = darray_reserve(vulkan_fence*, context.swapchain.image_count);
L490: if (context.images_in_flight[context.image_index] != 0) {  // was frame

**Comment by travisvroman** [comment]
Good catch, thank you! 

The code varies slightly at this point because of changes made in the between time, but this is now fixed.
