### ISSUE TITLE
Build With CMake.

### ISSUE THREAD

**Issue by Ghostdev84** [travisvroman/kohi#202]
pls, add cmakelists.txt files to the project so it can be built with CMake.

**Comment by Cankar001** [comment]
Please no xD cmake is awful, I have to use it at work xD Better use premake or xmake, or just makefiles

**Comment by travisvroman** [comment]
Thanks for submitting this, but this isn't going to happen anytime soon (if ever). This isn't a project with lots of dependencies that need to be managed. CMake is overkill, and frankly something I'm not interested in maintaining. The makefiles here do everything that's needed so long as you pass the right arguments to them. Feel free to maintain a local .gitignored cmakelists.txt if you wish.
