### ISSUE TITLE
[BUG] Cannot compile on Linux because of VLAs

### ISSUE THREAD

**Issue by AlexJustRandom** [travisvroman/kohi#21]
**Describe the bug**
While building i'am getting error:
```$ '/home/alex/Desktop/kohi/build-all.sh' 
Building everything...
Scaffolding folder structure...
Done.
Compiling...
engine/src/renderer/renderer_frontend.c...
engine/src/renderer/renderer_frontend.c:170:15: error: variable length array used [-Werror,-Wvla]
    u8 pixels[pixel_count * channels];
              ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile.engine.linux.mak:43: obj/engine/src/renderer/renderer_frontend.c.o] Error 1
Error:2
```
 - OS: Linux / Manjaro 
 
All required libs are installed 
clang version: clang-12

**Comment by 2nafish117** [comment]
The compiler flags -Werror -Wvla considers all warnings as errors and variable length arrays as errors. You cannot use variable length arrays like `u8 pixels[pixel_count * channels];`

**Comment by travisvroman** [comment]
Dang, I thought I had gotten rid of all of them. This is now in `texture_system.c`. I'll update this soon.
Going to use `-Werror -Wvla -Wgnu-folding-constant` on Windows builds so this gets caught (found a couple others also).

**Comment by travisvroman** [comment]
This was fixed in this commit: https://github.com/travisvroman/kohi/commit/de996b0b926c66e11bd23417e41d36181d5df273
