### ISSUE TITLE
[BUG] Clang on Windows not recognizing "stdio.h"

### ISSUE THREAD

**Issue by codinggamingandmhs** [travisvroman/kohi#225]
Clang on windows is saying:
"Building for Windows..."
"Building everything on windows (debug)..."
--- Performing "versiongen" debug build ---
  versiongen/src/main.c...
versiongen/src/main.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [Makefile.executable.mak:142: obj/versiongen/src/main.c.o] Error 1
Error:2

**To Reproduce**
1. Type "build-debug"
2. See error

**Expected behavior**
The engine to build

**Specs:**
 - OS: Microsoft Windows 11 23H2
 - Compiler: Latest version of Clang (although I like GCC most)
 - Visual Studio Community 2022 & 2019

**Comment by IvanPostu** [comment]
Hi, I've had exactly this issue for Windows 10, here is how I tackled it:
- Install Visual Studio Community
  - In Visual Studio Installer, select `Desktop development with C++`
  ![image](https://github.com/travisvroman/kohi/assets/48165593/34444e9a-d735-48ca-a8e5-9ceb51c66832)
- Reinstall `clang`

**Comment by codinggamingandmhs** [comment]
I'll try reinstalling `clang`. Thank you for the help!

**Comment by codinggamingandmhs** [comment]
Huh. It didn't work.

**Comment by codinggamingandmhs** [comment]
I've also tried using VS 2022's command prompt. It might be a clang problem, because it didn't do that to me with `gcc`. That's why I use it. Not that I'm against Travis.

**Comment by codinggamingandmhs** [comment]
Do I have to spam stuff? It doesn't work with GCC either, it spits out 30 error messages. (Literally.)

**Comment by travisvroman** [comment]
@codinggamingandmhs 
Just catching up on issues - apologies for the delay. I've had issues installing clang via the VS installer. What I've always done in the past is install VS with the C++ build tools and _then_ install clang via the clang installer from their site. I had this be the process I had to use as recently as a month ago. Give this a shot and let me know if it helps.

I need to put aside some time to come up with a newer, up-to-date process for this that is documented, it seems.

**Comment by codinggamingandmhs** [comment]
I think I fixed it. Thanks for the help, @travisvroman and @IvanPostu .
