### ISSUE TITLE
[FEATURE] VSCode Terminal Setting - Integrated Font Family (settings.json)

### ISSUE THREAD

**Issue by nickscha** [travisvroman/kohi#23]
**Is your feature request related to a problem? Please describe.**
In the current VS Code Version 1.63.2 a "bug" can occur which causes an widely spaced font setting in the Terminal window.
See: https://github.com/microsoft/vscode/issues/120004

On a fresh installation of VSCode the Terminal (Windows 10, Powershell 7) looks like this (spaced out letters):

![vscode_kohi_terminal_before](https://user-images.githubusercontent.com/28190285/147566739-90b10063-7653-4137-a676-ed299a838c99.PNG)

**Describe the solution you'd like**

In **".vscode/settings.json"**  the entry **"terminal.integrated.fontFamily": "Consolas",** could be added which resolves to a proper spacing:

![vscode_kohi_terminal_after_integrated_font_family](https://user-images.githubusercontent.com/28190285/147566741-15999191-3dff-4a1a-b7ee-ae5043e18e30.PNG)

**Describe alternatives you've considered**

The "letterSpacing" property mentioned in "https://github.com/microsoft/vscode/issues/120004" did not work in my case.

**Comment by travisvroman** [comment]
Removed the font setting altogether so it will just use what's on the platform.
