### ISSUE TITLE
My second try at compiling Kohi. I don't understant what is this.

### ISSUE THREAD

**Issue by ElectricLizzzard** [travisvroman/kohi#236]
![зображення](https://github.com/user-attachments/assets/ab433ccc-6f0d-4f53-8271-5aaae29e4e88)

**Comment by ElectricLizzzard** [comment]
I have managed to resolve dependency errors, build-release.sh compiled the engine with no errors but still no luck of booting the software.

![зображення](https://github.com/user-attachments/assets/ea9684b7-f6d0-442a-8fb2-d24da16089cc)

**Comment by ElectricLizzzard** [comment]
I have roselved vulkan-validation-layer problem, but still not luck.

![зображення](https://github.com/user-attachments/assets/8623bbdd-f251-4840-ba14-aa7c777ccac3)

**Comment by travisvroman** [comment]
Pretty sure we covered this on stream. You're running the unit tests here, not the 'Testbed' executable. Closing.
