### ISSUE TITLE
[BUG] Vulkan Device creation fails when transfer queue and present queue are the same

### ISSUE THREAD

**Issue by matthewsgc** [travisvroman/kohi#26]
For some graphics cards, the current queue selection process will lead to the transfer and present queues being the same queue. The code then assumes these two are separate. 

The relevant section of the vulkaninfo extract for the AMD Radeon RX 5700 XT is included below, as well as suggested code changes.

VkQueueFamilyProperties:
========================
	queueProperties[0]:
	-------------------
		minImageTransferGranularity = (1,1,1)
		queueCount                  = 1
		queueFlags                  = QUEUE_GRAPHICS | QUEUE_COMPUTE | QUEUE_TRANSFER | QUEUE_SPARSE_BINDING
		timestampValidBits          = 64
		present support             = true

	queueProperties[1]:
	-------------------
		minImageTransferGranularity = (1,1,1)
		queueCount                  = 2
		queueFlags                  = QUEUE_COMPUTE | QUEUE_TRANSFER | QUEUE_SPARSE_BINDING
		timestampValidBits          = 64
		present support             = true

	queueProperties[2]:
	-------------------
		minImageTransferGranularity = (16,16,8)
		queueCount                  = 2
		queueFlags                  = QUEUE_TRANSFER | QUEUE_SPARSE_BINDING
		timestampValidBits          = 64
		present support             = true

vulkan_device.c

    // GM: added this to cater for overlap of transfer and present queues
    b8 transfer_shares_present_queue = context->device.transfer_queue_index == context->device.present_queue_index;
    u32 index_count = 1;
    if (!present_shares_graphics_queue) {
        index_count++;
    }
    if (!transfer_shares_graphics_queue) {
        index_count++;
    }
    // GM: added this if statement to cater for overlap of transfer and present queues
    if (transfer_shares_present_queue) {
        index_count--;
    }
    u32 indices[32];
    u8 index = 0;
    indices[index++] = context->device.graphics_queue_index;
    if (!present_shares_graphics_queue) {
        indices[index++] = context->device.present_queue_index;
    }
    // GM: altered this if statement to cater for overlap of transfer and present queues
    if (!transfer_shares_graphics_queue && !transfer_shares_present_queue) {
        indices[index++] = context->device.transfer_queue_index;
    }

**Comment by travisvroman** [comment]
@matthewsgc Had a think about this on my lunch break today and put in a different fix for this that instead prefers sharing the graphics and present queues, but still uses a separate queue for transfers. This should also fix your issue here. 

Please try the `bugfix/26` branch and let me know if this solves this for you.

**Comment by matthewsgc** [comment]
This solves the problem on my end. Thanks.
