### ISSUE TITLE
Free List requires far more memory than the memory it manages [BUG]

### ISSUE THREAD

**Issue by matthewsgc** [travisvroman/kohi#28]
freelist.c 
u64 max_entries = (total_size / sizeof(void*));  //NOTE: This might have a remainder, but that's ok.

When running the application, the memory usage from the OS indicates 4GB usage, when you're managing only 1GB.
This calculation will need to make an assumption that not every request will be as small as a void* to be efficient.

Maybe...
u64 max_entries = (total_size / (16 * sizeof(void*)));  //NOTE: This might have a remainder, but that's ok.

**Comment by travisvroman** [comment]
Oof, was missing part of the equation there. You were close, but I actually need to use the size of the node itself for this, which actually reduces it further. Thanks for finding this and for reporting it!
