### ISSUE TITLE
Potential bug in platform_win32.c, platform_console_write_error...

### ISSUE THREAD

**Issue by theoldnewb** [travisvroman/kohi#37]
Hello Travis,

Thank you for the kohi series on youtube.
Since, I don't have a youtube account. I will post this here.
I believe there is a potential bug in the platform_win32.c 
In the function 'platform_console_write_error'

```
LPDWORD number_written = 0;

WriteConsoleA(GetStdHandle(STD_ERROR_HANDLE), message, (DWORD)length, number_written, 0);

```

If I am not mistaken then I believe that the 'number_written' variable is not used properly.
My gut feeling about the Windows API tells me that it probably would need to be something like this:

```
DWORD number_written = 0;

WriteConsoleA(GetStdHandle(STD_ERROR_HANDLE), message, (DWORD)length, &number_written, 0);

```

I don't think it is too big of an issue here, because the LPDWORD is technically a null pointer.
If it had not been initialized to 0. the WriteConsoleA function could have probably thrashed some memory.

Kind regards,
theoldnewb

**Comment by travisvroman** [comment]
You are correct! Thanks for reporting this.

**Comment by theoldnewb** [comment]
No problem.

**Comment by travisvroman** [comment]
It's not fixed _yet_. :) Reopening.
