### ISSUE TITLE
filesystem_exists() _MSC_VER

### ISSUE THREAD

**Issue by furious114** [travisvroman/kohi#47]
**Describe the bug**
This function never caused an issue until now because it doesn't check against 0, basically returned the opposite of what is expected. solution: return _stat(path, &buffer) == 0;

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by travisvroman** [comment]
Good catch! I did actually find this one, and it gets fixed in a future video. I'll leave this open in the meantime though. Thank you!

**Comment by travisvroman** [comment]
Previously fixed.

**Comment by ghost** [comment]
Where is this fixed?
