### ISSUE TITLE
[BUG] Assets failing to load

### ISSUE THREAD

**Issue by urcereal** [travisvroman/kohi#49]
Are we missing a few assets?

[ERROR]: Image resource loader failed to load file '../assets/textures/orange_lines_512.tga'.
[ERROR]: Failed to load image resource for texture 'orange_lines_512'
[ERROR]: Failed to load texture 'orange_lines_512'.
[WARN]:  Unable to load texture 'orange_lines_512' for material 'test_material', using default.
[ERROR]: Image resource loader failed to load file '../assets/textures/orange_lines_512_SPEC.tga'.

[ERROR]: Error opening file: '../assets/models/falcon.ksm'
[ERROR]: Unable to find mesh of supported type called 'falcon'.
[ERROR]: Failed to load car test mesh!
Did a clone and a clean build and also ran post build.

**Comment by furious114** [comment]
that's because of an issue of the function filesystem_exists(): https://github.com/travisvroman/kohi/issues/47

**Comment by travisvroman** [comment]
I just double-checked this with a fresh clone just to be sure, and all the assets are there, and it runs. Perhaps another pull is needed? I did wind up merging the PR a bit late after the video's release, so it's possible that it wasn't up to date yet if that's when you pulled.

Also, the text in the log above saying it can't find the mesh of supported type 'falcon' makes me think for some reason your code is treating the name of the mesh as the extension. 

If this is on Windows, there is a filesystem issue as well as mentioned by @furious114, #47  

Does it work if you apply the suggested fix there?

**Comment by urcereal** [comment]
Yep, the furious114 answer is the solution. Thanks guys.

**Comment by travisvroman** [comment]
This will be fixed by #47. Closing this.
