### ISSUE TITLE
[BUG] Small memory leak when searching for device requirements

### ISSUE THREAD

**Issue by travisvroman** [travisvroman/kohi#54]
**Describe the bug**
Reported in YT comments. In `vulkan_device.c`, around line 322 the `requirements.device_exctension_names` darray is created, but not destroyed after the call to `physical_device_meets_requirements`. 

Instead of just adding this though, that whole block should be moved outside the loop, and the darray finally destroyed once the loop completes, before the check to see if a device was selected.

Edit: Also includes `required_validation_layer_names` and `available_layers` in `vulkan_backend.c` around line 242.

**Comment by beewyka819** [comment]
Is it intentional that both `required_validation_layer_names` and `required_extensions` are only freed in debug builds? I feel like these should also be getting freed in release builds. They are inside an `#if defined(_DEBUG)` block at `vulkan_backend.c:175`.

**Comment by travisvroman** [comment]
Thank you for opening this. It is, however a duplicate of #58, and will be fixed there instead.
