### ISSUE TITLE
[BUG] freelist_create - Changing max_entries breaks the freelist tests

### ISSUE THREAD

**Issue by YEEEEEEEEEES** [travisvroman/kohi#59]
**Describe the bug**
Changing the max_entries from
```
u64 max_entries = total_size / sizeof(void*);
```
to
```
u64 max_entries = total_size / (sizeof(void*) * sizeof(freelist_node));
```
makes the unit tests fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/46153861/169842800-07c5f6c6-9a9e-4510-9df7-b7b89167b814.png)
![image](https://user-images.githubusercontent.com/46153861/169842952-d631b7b1-e3e6-495f-af84-4cee0f43acfd.png)
![image](https://user-images.githubusercontent.com/46153861/169843046-d8cba17b-f104-49e7-bc1a-19af21432998.png)

**Desktop**
 - OS: Windows 10

**Comment by travisvroman** [comment]
Heh, good catch. Thanks for reporting it. I'm actually unsure how I didn't catch this before now.

**Comment by travisvroman** [comment]
Fixed.
