### ISSUE TITLE
[BUG] Linking Error (Windows)

### ISSUE THREAD

**Issue by furious114** [travisvroman/kohi#63]
**Describe the bug**
I've tried cleaning and rebuilding. Redownloaded into another folder.  .dll and .lib are built successfully. Not sure why I'm getting linking errors:

game.c.o : error LNK2019: unresolved external symbol camera_system_get_default referenced in function game_initialize
game.c.o : error LNK2019: unresolved external symbol camera_position_set referenced in function game_initialize
game.c.o : error LNK2019: unresolved external symbol camera_yaw referenced in function game_update
game.c.o : error LNK2019: unresolved external symbol camera_pitch referenced in function game_update
game.c.o : error LNK2019: unresolved external symbol camera_move_forward referenced in function game_update
game.c.o : error LNK2019: unresolved external symbol camera_move_backward referenced in function game_update
game.c.o : error LNK2019: unresolved external symbol camera_move_left referenced in function game_update
game.c.o : error LNK2019: unresolved external symbol camera_move_right referenced in function game_update
game.c.o : error LNK2019: unresolved external symbol camera_move_up referenced in function game_update
game.c.o : error LNK2019: unresolved external symbol camera_move_down referenced in function game_update
bin\testbed.exe : fatal error LNK1120: 11 unresolved externals
clang: error: linker command failed with exit code 1120 (use -v to see invocation)

**Comment by S-Marais** [comment]
In camera.h just put KAPI in front of the functions declarations.

**Comment by travisvroman** [comment]
Thanks for reporting this!

This was fixed in video 66. The suggestion by @S-Marais is indeed the fix. The latest code has this as well. Closing.
