### ISSUE TITLE
[BUG] vulkan_command_buffer_create has incorrect size when zeroing out_command_buffer

### ISSUE THREAD

**Issue by beewyka819** [travisvroman/kohi#76]
See the following line:
https://github.com/travisvroman/kohi/blob/97b4b5bb02fafcc852fcaea9c73e771ed5e82542/engine/src/renderer/vulkan/vulkan_command_buffer.c#L11
This should be `sizeof(vulkan_command_buffer)`, as `sizeof(out_command_buffer)` will just return the size of the pointer, not the struct itself.

**Comment by travisvroman** [comment]
Thank you for opening this! It is, however, a duplicate of #58 and is fixed there.
